title:            Sou Criador
description:      desenvolvedor de experiências
disqus_shortname: soucriador
#Your site's domain goes here. Leave localhost server or blank when working locally.
#url:              http://127.0.0.1:4000
url:              https://blog.soucriador.com/

# Owner/author information
owner:
  name:           Jhonattas
  avatar:         avatar.jpg
  bio:            "A developer who loves beautiful things."
  email:          jhonattas@soucriador.com
  # Social networking links used in footer. Update and remove as you like.
  #facebook:       jhoouh
  github:         jhonattas
  #stackexchange:  
  #flickr:         
  #tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  #google_plus:   https://plus.google.com/+JhonattasGonçalves/
  linkedin:       jhonattas
  instagram:      jhonattash
  twitter:        jhoouh

# Background image to be tiled on all pages
background: ps_neutral.png

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-41843022-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
#links:
#  - title: Theme Setup
#    url: /theme-setup
#  - title: External Link
#    url: http://mademistakes.com
#    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:   America/Sao_Paulo
future:     true
rouge:      true
markdown:   kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: true

  syntax_highlighter_opts:
    line_numbers: nil
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

plugins: [jekyll-paginate, jekyll-json-feed]

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
